import { type Static, Type } from "typebox";

import { ImageDataContent, TextContent } from "./contents";
import { ToolCall } from "./tools";
import { ModelUsage } from "./usage";

/**
 * The allowed content types of a user message.
 */
export const UserMessageContent = Type.Union([TextContent, ImageDataContent]);
export type UserMessageContent = ImageDataContent | TextContent;

export const SandboxAttachmentDescriptor = Type.Object({
  id: Type.String({ minLength: 1 }),
  name: Type.String({
    minLength: 1,
    maxLength: 240,
    pattern: "^[^/\\\\\\x00-\\x1f\\x7f]+$"
  }),
  path: Type.String({ pattern: "^/workspace/attachments/" }),
  size: Type.Integer({ minimum: 0, maximum: 25 * 1024 * 1024 }),
  fingerprint: Type.String({ pattern: "^[0-9a-f]{64}$" }),
  mimeType: Type.Optional(Type.String())
});
export type SandboxAttachmentDescriptor = Static<
  typeof SandboxAttachmentDescriptor
>;

/**
 * A message sent from user.
 */
export const UserMessage = Type.Object({
  /**
   * The unique ID of the message.
   */
  id: Type.String(),

  /**
   * The role of the message.
   */
  role: Type.Literal("user"),

  /**
   * The content of the message.
   */
  content: Type.Array(UserMessageContent),
  attachments: Type.Optional(Type.Array(SandboxAttachmentDescriptor))
});
export type UserMessage = Static<typeof UserMessage>;

/**
 * The allowed content types of a assistant message.
 */
export const AssistantMessageContent = Type.Union([TextContent]);

/**
 * A message generated by AI.
 */
export const AssistantMessage = Type.Object({
  /**
   * The unique ID of the message.
   */
  id: Type.String(),

  /**
   * The role of the message.
   */
  role: Type.Literal("assistant"),

  /**
   * The content of the message.
   */
  content: Type.Array(AssistantMessageContent),

  /**
   * The thinking of the message.
   */
  thinking: Type.Optional(Type.String()),

  /**
   * The tool calls of the message.
   */
  toolCalls: Type.Optional(Type.Array(ToolCall)),

  /**
   * Provider-reported token usage for this completed assistant/model step.
   */
  usage: Type.Optional(ModelUsage)
});
export type AssistantMessage = Static<typeof AssistantMessage>;

/**
 * The union type of the message.
 */
export const Message = Type.Union([UserMessage, AssistantMessage]);
export type Message = AssistantMessage | UserMessage;

/**
 * The plain text of a message: its text content parts joined by newlines.
 * Non-text content (e.g. images) is ignored.
 */
export function getMessageText(message: Message): string {
  const parts: string[] = [];
  for (const c of message.content) {
    if (c.type === "text") {
      parts.push(c.text);
    }
  }
  return parts.join("\n");
}

export function formatSandboxAttachmentsForPi(
  attachments: readonly SandboxAttachmentDescriptor[]
): string {
  return [
    "<attachments>",
    ...attachments.map(attachment =>
      `- ${attachment.name}: ${attachment.path}`),
    "</attachments>"
  ].join("\n");
}
